### ISSUE TITLE
Multiplayer matches seem to crash bancho (?)

### ISSUE THREAD

**Issue by Lekuruu** [osuTitanic/anchor#360]
Recently, there have been some crashes to Bancho, which I thought were happening because I ran out of memory. But just to be safe, I should be testing this again.

**Comment by Zordon1337** [comment]
Maybe lets flood multiplayer with test accounts and check what happens?

**Comment by Lekuruu** [comment]
Nope, it didn't crash bancho when I tested it.

**Comment by how-to-do-frontend** [comment]
> Nope, it didn't crash bancho when I tested it.

your testing was fucking torture

**Comment by Lekuruu** [comment]
> your testing was fucking torture

Ah yes, right.
![image](https://github.com/user-attachments/assets/ec954235-ef68-4fbe-b9e6-45197f8eaac7)

**Comment by how-to-do-frontend** [comment]
where is the 2nd player

**Comment by Lekuruu** [comment]
> where is the 2nd player

Left the match
